### PR TITLE
Change method named 'done' to 'is_done', Cus is just a check.

### PR DESCRIPTION
**Pull request by leaofelipe**

### CODE REVIEW

**Comment by raphamorim** [comment]
Hm, that's true. But we using javascript, so camelCase is better right?

What do you think about `isDone` ?

**Comment by leaofelipe** [comment]
Yeah, but when i see the code Style, there's another method called `is_cached`. So my intention was follow the convention :)

**Comment by raphamorim** [comment]
Whoa, I've forgot change this method name. My mistake sorry.
So in this PR you can update name to `_isCached` ?

Cause is "private" method.

**Comment by raphamorim** [comment]
And update to `_fail`, `_ready`  methods too :)

**Comment by leaofelipe** [comment]
Right! I'll set another Pull Request with these changes.

**Comment by raphamorim** [comment]
thnx :)

**Pull request merged**
