### PR TITLE
Code Style changes on methods:

### PR DESCRIPTION
**Pull request by leaofelipe**
- `ready` is now `setLoaded`, because it increments a loaded value.
- `fail` is now `setFailed`, because it increments a failed value.

What do you think?

### CODE REVIEW

**Comment by raphamorim** [comment]
Nice, but use this methods name as "private" like: `_setLoaded` and `_setFailed`.

I'll update window.imgStatus later, so this "fix" our problem with global methods.

**Comment by leaofelipe** [comment]
Changed! Take a look.

**Comment by raphamorim** [comment]
Thanks :)

**Comment by leaofelipe** [comment]
:octocat:

**Pull request merged**
